ENV = 'development'
FLASK_ENV = 'development'
DEBUG = True
SECRET_KEY = b't\xd9\xd8:0\xff[\xbaIm\xbeK\x92\xcc*'
SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite3'
SQLALCHEMY_TRACK_MODIFICATIONS = False
UPLOAD_FOLDER = '.\\uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
JWT_SECRET_KEY = '20RUSF093YFH98fy94bt98y93qohtp98fpg3i4utbgf'
